# Generated by Django 5.1.5 on 2025-02-05 21:45

import django.db.models.deletion
import planificacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.TextField()),
                ('materia', models.TextField()),
                ('carrera', models.TextField()),
                ('semestre', models.CharField(default='Unknown', max_length=10)),
                ('numero_actividad', models.IntegerField(default=0)),
                ('tema', models.TextField()),
                ('trabajo_independiente', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=planificacion.models.unique_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='FormasEnse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecursosDidacticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TecnicaCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrabajoFecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(blank=True, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to=planificacion.models.unico_archivo)),
            ],
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_nombre', models.TextField(blank=True, null=True)),
                ('saludo', models.TextField(blank=True, null=True)),
                ('bibliografia', models.TextField(blank=True, null=True)),
                ('evaluacion_aprendizaje', models.TextField(blank=True, null=True)),
                ('an_tecnica_cierre', models.TextField(blank=True, null=True)),
                ('chequeo_trabajo', models.TextField(blank=True, null=True)),
                ('trabajo_independiente', models.TextField(blank=True, null=True)),
                ('actividad_docente', models.CharField(max_length=300)),
                ('asistencia', models.TextField(blank=True, null=True)),
                ('motivacion', models.TextField(blank=True, null=True)),
                ('objetivo', models.TextField(blank=True, null=True)),
                ('desarrollo_clase', models.TextField()),
                ('conclusion', models.CharField(blank=True, max_length=300, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ejecucion', models.DateField(blank=True, null=True)),
                ('forma_ense', models.ManyToManyField(to='planificacion.formasense')),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificacion.metodos')),
                ('numero_actividad', models.ManyToManyField(related_name='planes', to='planificacion.anexo1')),
                ('recurso_didactico', models.ManyToManyField(to='planificacion.recursosdidacticos')),
                ('tecnica_cierre', models.ManyToManyField(related_name='planes', to='planificacion.tecnicacierre')),
                ('trabajo_fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificacion.trabajofecha')),
            ],
        ),
    ]
