# Generated by Django 5.1.4 on 2025-01-17 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anexo1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente', models.TextField()),
                ('materia', models.TextField()),
                ('carrera', models.TextField()),
                ('actividad', models.CharField(max_length=300)),
                ('tema', models.TextField()),
                ('trabajo_independiente', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormasEnse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecursosDidacticos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Saludo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saludo', models.CharField(max_length=500)),
                ('asignatura', models.IntegerField()),
                ('docente', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TecnicaCierre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_actividad', models.CharField(max_length=100)),
                ('actividad_docente', models.CharField(max_length=300)),
                ('asistencia', models.CharField(max_length=400)),
                ('trabajo_fecha', models.CharField(max_length=400)),
                ('trabajo_independiente', models.CharField(max_length=400)),
                ('motivacion', models.CharField(max_length=800)),
                ('objetivo', models.CharField(max_length=800)),
                ('desarrollo_clase', models.JSONField()),
                ('conclusion', models.CharField(max_length=300)),
                ('evaluacion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('anexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificacion.anexo1')),
                ('forma_ense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificacion.formasense')),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificacion.metodos')),
                ('recurso_didactico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificacion.recursosdidacticos')),
                ('tecnica_cierre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planificacion.tecnicacierre')),
            ],
        ),
    ]
