# Generated by Django 5.1.5 on 2025-02-06 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabajofecha',
            name='descripcion',
        ),
    ]
