# Generated by Django 5.1.4 on 2025-01-22 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo1',
            name='semestre',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
