# Generated by Django 5.1.5 on 2025-04-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0002_remove_trabajofecha_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes',
            name='archivo_firmado',
            field=models.FileField(blank=True, null=True, upload_to='planes_firmados/'),
        ),
    ]
