# Generated by Django 5.1.4 on 2025-01-22 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0002_anexo1_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexo1',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='anexo/'),
        ),
        migrations.AlterField(
            model_name='anexo1',
            name='semestre',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
