# Generated by Django 5.1.4 on 2025-01-22 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0003_anexo1_archivo_alter_anexo1_semestre'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='anexo1',
            unique_together={('materia', 'semestre')},
        ),
    ]
