# Generated by Django 5.1.4 on 2025-01-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0004_alter_anexo1_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='anexo1',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='anexo1',
            constraint=models.UniqueConstraint(fields=('materia', 'semestre', 'archivo'), name='unique_materia_semestre_archivo'),
        ),
    ]
