# Generated by Django 5.1.4 on 2025-01-22 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0005_alter_anexo1_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='anexo1',
            name='unique_materia_semestre_archivo',
        ),
    ]
