# Generated by Django 5.1.4 on 2025-01-22 21:20

import planificacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0006_remove_anexo1_unique_materia_semestre_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo1',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=planificacion.models.unique_file_path),
        ),
    ]
