# Generated by Django 5.1.4 on 2025-01-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0007_alter_anexo1_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saludo',
            name='asignatura',
        ),
        migrations.AddField(
            model_name='saludo',
            name='materia',
            field=models.TextField(default='Unknown'),
        ),
    ]
