# Generated by Django 5.1.4 on 2025-01-22 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0008_remove_saludo_asignatura_saludo_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saludo',
            name='saludo',
            field=models.TextField(),
        ),
    ]
