# Generated by Django 5.1.4 on 2025-01-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0009_alter_saludo_saludo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saludo',
            name='docente',
            field=models.TextField(default='Unknown'),
        ),
    ]
