# Generated by Django 5.1.4 on 2025-01-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0010_alter_saludo_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planes',
            name='trabajo_independiente',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='recurso_didactico',
        ),
        migrations.AddField(
            model_name='planes',
            name='recurso_didactico',
            field=models.ManyToManyField(to='planificacion.recursosdidacticos'),
        ),
    ]
