# Generated by Django 5.1.4 on 2025-01-23 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0011_remove_planes_trabajo_independiente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes',
            name='plan_nombre',
            field=models.TextField(default='Unknown'),
        ),
    ]
