# Generated by Django 5.1.4 on 2025-01-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0012_planes_plan_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes',
            name='saludo',
            field=models.TextField(default='Unknown'),
        ),
    ]
