# Generated by Django 5.1.4 on 2025-01-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0013_planes_saludo'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes',
            name='analisis_tecnica_cierre',
            field=models.TextField(default='Unknown'),
        ),
        migrations.AddField(
            model_name='planes',
            name='chequeo_trabajo',
            field=models.TextField(default='Unknown'),
        ),
    ]
