# Generated by Django 5.1.4 on 2025-01-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0014_planes_analisis_tecnica_cierre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes',
            name='evaluacion_aprendizaje',
            field=models.TextField(default='Unknown'),
        ),
    ]
