# Generated by Django 5.1.4 on 2025-01-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0016_planes_bibliografia'),
    ]

    operations = [
        migrations.AddField(
            model_name='planes',
            name='trabajo_independiente',
            field=models.TextField(default='Unknown'),
        ),
    ]
