# Generated by Django 5.1.4 on 2025-01-24 19:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0017_planes_trabajo_independiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes',
            name='desarrollo_clase',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
