# Generated by Django 5.1.4 on 2025-01-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0018_alter_planes_desarrollo_clase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planes',
            old_name='analisis_tecnica_cierre',
            new_name='an_tecnica_cierre',
        ),
        migrations.AddField(
            model_name='planes',
            name='fecha_ejecucion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planes',
            name='desarrollo_clase',
            field=models.TextField(),
        ),
    ]
