# Generated by Django 5.1.4 on 2025-01-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0020_alter_planes_fecha_ejecucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes',
            name='fecha_ejecucion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
