# Generated by Django 5.1.4 on 2025-01-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0021_alter_planes_fecha_ejecucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes',
            name='an_tecnica_cierre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planes',
            name='asistencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planes',
            name='bibliografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planes',
            name='chequeo_trabajo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planes',
            name='conclusion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='planes',
            name='evaluacion_aprendizaje',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planes',
            name='motivacion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planes',
            name='objetivo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planes',
            name='plan_nombre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planes',
            name='saludo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planes',
            name='trabajo_fecha',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='planes',
            name='trabajo_independiente',
            field=models.TextField(blank=True, null=True),
        ),
    ]
