# Generated by Django 5.1.4 on 2025-01-25 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0022_alter_planes_an_tecnica_cierre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planes',
            name='evaluacion',
        ),
    ]
