# Generated by Django 5.1.4 on 2025-01-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0023_remove_planes_evaluacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anexo1',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='anexo',
        ),
        migrations.AddField(
            model_name='anexo1',
            name='numero_actividad',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='planes',
            name='forma_ense',
        ),
        migrations.RemoveField(
            model_name='planes',
            name='numero_actividad',
        ),
        migrations.AddField(
            model_name='planes',
            name='forma_ense',
            field=models.ManyToManyField(to='planificacion.formasense'),
        ),
        migrations.AddField(
            model_name='planes',
            name='numero_actividad',
            field=models.ManyToManyField(related_name='planes', to='planificacion.anexo1'),
        ),
    ]
