# Generated by Django 5.1.4 on 2025-01-31 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planificacion', '0024_remove_anexo1_actividad_remove_planes_anexo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planes',
            name='tecnica_cierre',
        ),
        migrations.AddField(
            model_name='planes',
            name='tecnica_cierre',
            field=models.ManyToManyField(related_name='planes', to='planificacion.tecnicacierre'),
        ),
    ]
